/* Generated By:JJTree: Do not edit this line. ASTArithmetic.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArithmetic extends SimpleNode {
  public ASTArithmetic(int id) {
    super(id);
  }

  public ASTArithmetic(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b49a43c487166ddc4df822c5aa44c305 (do not edit this line) */
