/* Generated By:JJTree: Do not edit this line. ASTArithOp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArithOp extends SimpleNode {
  public ASTArithOp(int id) {
    super(id);
  }

  public ASTArithOp(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a3f947ffaea58bdfa592a437c788bc2e (do not edit this line) */
