/* Generated By:JJTree: Do not edit this line. ASTDeclare.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeclare extends SimpleNode {
  public ASTDeclare(int id) {
    super(id);
  }

  public ASTDeclare(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=396cf891b3cb4c7a3f358c297e279652 (do not edit this line) */
