/* Generated By:JJTree: Do not edit this line. ASTELSEIF.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTELSEIF extends SimpleNode {
  public ASTELSEIF(int id) {
    super(id);
  }

  public ASTELSEIF(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b5e25ed1b7f43b25375d2c7a4ca36d52 (do not edit this line) */
