/* Generated By:JJTree: Do not edit this line. ASTFOR.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFOR extends SimpleNode {
  public ASTFOR(int id) {
    super(id);
  }

  public ASTFOR(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a0fd3cc8498e910d6d31341f0262e07 (do not edit this line) */
