/* Generated By:JJTree: Do not edit this line. ASTInterrupt.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInterrupt extends SimpleNode {
  public ASTInterrupt(int id) {
    super(id);
  }

  public ASTInterrupt(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2555335cb29d5d03895ff91d9902d7b4 (do not edit this line) */
