/* Generated By:JJTree: Do not edit this line. ASTLogicOp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLogicOp extends SimpleNode {
  public ASTLogicOp(int id) {
    super(id);
  }

  public ASTLogicOp(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4996d1240d3b34e2350ac36c765912d9 (do not edit this line) */
