/* Generated By:JJTree: Do not edit this line. ASTPositive.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPositive extends SimpleNode {
  public ASTPositive(int id) {
    super(id);
  }

  public ASTPositive(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8f0821c2eca2d78f79eb701d398559f9 (do not edit this line) */
