/* Generated By:JJTree: Do not edit this line. ASTProcedure.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTProcedure extends SimpleNode {
  public ASTProcedure(int id) {
    super(id);
  }

  public ASTProcedure(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b962033642da46030b2a76cb6fb5292f (do not edit this line) */
