/* Generated By:JJTree: Do not edit this line. ASTRelationOp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRelationOp extends SimpleNode {
  public ASTRelationOp(int id) {
    super(id);
  }

  public ASTRelationOp(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=63dffb80dc2352b970cea86ee5a44b38 (do not edit this line) */
