/* Generated By:JJTree: Do not edit this line. ASTRelation.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRelation extends SimpleNode {
  public ASTRelation(int id) {
    super(id);
  }

  public ASTRelation(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=01a825cd5c9801b0e08696ac6101f3ed (do not edit this line) */
