/* Generated By:JavaCC: Do not edit this line. CMMTreeConstants.java Version 6.0_1 */
public interface CMMTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROCEDURE = 1;
  public int JJTSTATEMENT = 2;
  public int JJTDECLARE = 3;
  public int JJTASSIGNMENT = 4;
  public int JJTVOID = 5;
  public int JJTTYPE = 6;
  public int JJTINDEX = 7;
  public int JJTASSIGN = 8;
  public int JJTPARAMETER = 9;
  public int JJTCONASSIGN = 10;
  public int JJTIF = 11;
  public int JJTELSEIF = 12;
  public int JJTWHILE = 13;
  public int JJTFOR = 14;
  public int JJTINTERRUPT = 15;
  public int JJTRESULT = 16;
  public int JJTLOGIC = 17;
  public int JJTLOGICOP = 18;
  public int JJTRELATION = 19;
  public int JJTRELATIONOP = 20;
  public int JJTARITHMETIC = 21;
  public int JJTARITHOP = 22;
  public int JJTVARIABLE = 23;
  public int JJTMYID = 24;
  public int JJTSYMBOLVAR = 25;
  public int JJTCALL = 26;
  public int JJTARGUMENT = 27;
  public int JJTDIGIT = 28;
  public int JJTPOSITIVE = 29;


  public String[] jjtNodeName = {
    "Start",
    "Procedure",
    "Statement",
    "Declare",
    "Assignment",
    "void",
    "Type",
    "Index",
    "Assign",
    "Parameter",
    "ConAssign",
    "IF",
    "ELSEIF",
    "WHILE",
    "FOR",
    "Interrupt",
    "Result",
    "Logic",
    "LogicOp",
    "Relation",
    "RelationOp",
    "Arithmetic",
    "ArithOp",
    "Variable",
    "MyID",
    "SymbolVar",
    "Call",
    "Argument",
    "Digit",
    "Positive",
  };
}
/* JavaCC - OriginalChecksum=61dd0d92b72f686229d2e9a1f71f42c3 (do not edit this line) */
