/* Generated By:JJTree: Do not edit this line. ASTConAssign.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConAssign extends SimpleNode {
  public ASTConAssign(int id) {
    super(id);
  }

  public ASTConAssign(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=def95d32ee88462199051614b1d79c5d (do not edit this line) */
