/* Generated By:JJTree: Do not edit this line. ASTDigit.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDigit extends SimpleNode {
  public ASTDigit(int id) {
    super(id);
  }

  public ASTDigit(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=732f01f313635bac470b4c169ad4a2cb (do not edit this line) */
