/* Generated By:JJTree: Do not edit this line. ASTLogic.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLogic extends SimpleNode {
  public ASTLogic(int id) {
    super(id);
  }

  public ASTLogic(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7be5851a2c88293b73919da01579e0ee (do not edit this line) */
