/* Generated By:JJTree: Do not edit this line. ASTResult.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTResult extends SimpleNode {
  public ASTResult(int id) {
    super(id);
  }

  public ASTResult(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=abd242d97469477ad39bcbaf76c47558 (do not edit this line) */
