/* Generated By:JJTree: Do not edit this line. ASTSymbolVar.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSymbolVar extends SimpleNode {
  public ASTSymbolVar(int id) {
    super(id);
  }

  public ASTSymbolVar(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a3e0f2a903dcb7e223bfbf3169629652 (do not edit this line) */
