/* Generated By:JJTree: Do not edit this line. ASTVariable.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVariable extends SimpleNode {
  public ASTVariable(int id) {
    super(id);
  }

  public ASTVariable(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=82d215ecfdfb54fd141613279659a518 (do not edit this line) */
