/* Generated By:JJTree: Do not edit this line. ASTWHILE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWHILE extends SimpleNode {
  public ASTWHILE(int id) {
    super(id);
  }

  public ASTWHILE(CMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=31354fbdbb40ed0d3b201159a87502c8 (do not edit this line) */
